spring.application.name=CodeChuyenNoi
google.api.key=YOUR_GOOGLE_API_KEY
google.oauth.client.secret.path=client_secret.json
ffmpeg.path=D:/ffmpeg-7.1.1-essentials_build/ffmpeg-7.1.1-essentials_build/bin/ffmpeg.exe
background.resources.path=D:\\anhtrutien
youtube.channel.id=YsOUR_CHANNEL_ID
story.base.url=https://truyenfull.vision/thay-phong-thuy/chuong-